#Recreate ValueError
print(int("10"))    #10
print(int("Rahul")) #ValueError: